services:
  bot_service:
    build:
      context: ./bot_service
      dockerfile: ./Dockerfile
    image: bot_service:latest
    ports:
      - "8000:8000"

  image_service:
    build:
      context: ./image_service
      dockerfile: ./Dockerfile
    image: image_service:latest
    ports:
      - "8001:8001"

  user_state_service:
    build:
      context: ./user_state_service
      dockerfile: ./Dockerfile
    image: user_state_service:latest
    ports:
      - "8002:8002"
